spring:
  application:
    name: redis
  redis:
    client-name: redis-client
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 50
    timeout: 5000
server:
  port: 8080
